#!/bin/bash
CONTAINER_NAME=beer_container
IMAGE_NAME=beer_image

which docker > /dev/null
[ "$?" != "0" ] && echo "Please install docker!" && exit 1

sudo docker build -t "$IMAGE_NAME" .
[ "$?" != "0" ] && echo "FAILED TO BUILD beer image!" && exit 1

sudo docker kill "$CONTAINER_NAME"
sudo docker rm -f "$CONTAINER_NAME" 


echo "start container"
PWD=$(pwd)

sudo docker run -tdi --name "$CONTAINER_NAME" -v $PWD/dist:/srv/BaseXWeb/static -p 1984:1984 -p 8984:8984 "$IMAGE_NAME":latest
./run_db_init.sh
